#install.packages("igraph")
library("igraph")
print("start")
dd<-as.matrix(read.table("C:/Users/james.raboin/Desktop/youtubeDM-master/com-amazon.ungraph.txt"))
#dd<-as.matrix(read.table("~/Documents/DM/graphV1000.txt"))
dd<-dd+1
graph_from_edgelist(dd, directed = FALSE)
gg <- graph_from_edgelist(cbind(dd), directed = FALSE)
#E(gg)$weight <- 1 
#simplify(gg, edge.attr.comb=list(weight="sum"))
#gg <- simplify(gg, remove.multiple = TRUE, remove.loops = TRUE)
#gg1 <- induced_subgraph(gg, 1:100000, impl = c("auto"))
#prune = which(transitivity(gg, type = c("local"), isolates = c("NaN", "zero")) != 0)
#plot(gg)
#delete_vertices(gg, prune)
time <- proc.time()
ebc <- cluster_fast_greedy(gg)
print("Time:")
pruned <- which(sizes(ebc)>2)
print(proc.time()-time)
membership(ebc)
sizes(ebc)
cc <- transitivity(gg, type = "local")
print(sum(cc, na.rm=TRUE)/length(cc))
print(length(V(gg)))
#MORE NODES HERE THAN IN DATASET
print(length(pruned))
adjmat <- as_adjacency_matrix(gg)
mg<-MCL::mcl(adjmat, addLoops = TRUE)
print(mg)