#install.packages("igraph")
library("igraph")
print("start")
dd<-as.matrix(read.table("~/Documents/DM/email-Eu-core.txt"))
#dd<-as.matrix(read.table("~/Documents/DM/graphV1000.txt"))
dd<-dd+1
graph_from_edgelist(dd, directed = FALSE)
gg <- graph_from_edgelist(cbind(dd), directed = FALSE)
#E(gg)$weight <- 1 
#simplify(gg, edge.attr.comb=list(weight="sum"))
gg <- simplify(gg, remove.multiple = TRUE, remove.loops = TRUE)
#gg1 <- induced_subgraph(gg, 1:100000, impl = c("auto"))
ebc <- cluster_walktrap(gg)
membership(ebc)
sizes(ebc)